# Generated by Django 3.2.18 on 2023-05-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='lng',
            field=models.DecimalField(decimal_places=13, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emote',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='emote',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.review'),
        ),
    ]
