# Generated by Django 3.2.18 on 2023-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230428_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
