# Generated by Django 3.2.18 on 2023-04-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
    ]
