# Generated by Django 3.2.18 on 2023-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230501_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
        migrations.AlterField(
            model_name='article',
            name='lng',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
    ]
