# Generated by Django 3.2.18 on 2023-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230428_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='emote',
            name='page',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
